### ISSUE TITLE
8月反省

### ISSUE THREAD

**Issue by 94yukari** [94yukari/edamame#17]
8/10,11に実施した実験関連の反省

**Comment by 94yukari** [comment]
〇ハード設計的な改善点
●減速比関連
・回転速度がはやい
・減速比の設計ミスnow16:1程度だがおそらく60:1ぐらい必要？
・減速比の再設計

→減速比を設計しなおす　必要トルク、回転速度、

●ゴムタイヤ
・取り付けにくい（コツがいる）
・タイヤ面とゴムタイヤの接点がシビア
・動力伝達がいい加減なのでタイヤに強く接すると高トルクで動かない
・ゴムタイヤと軸の固定
・ゴムタイヤ延長軸の強度(悪条件だと取れる)

→ゴムタイヤと軸の固定方法の検討
→ゴムタイヤと車輪の接点を柔軟に変えられる感じにする

●機構
・取り付け軸に対する左右の重さのバランス（モーメントで回転しがち）
・締結部に到達できるか？
・ネジ一つが車体と干渉（ただし、ワッシャを挟めば対処可）
・コの字型のＢＯＸの形状、サドルバンドでの固定は特に問題なし

→車体との固定箇所も考える
→穴をあける箇所も検討する

●その他
・物が重い
・8/8の様子だと、空で条件よければ自走できそうな雰囲気
・タイヤに汚れありー＞屋外で使用できるか？

〇電気関係
・電源スイッチが欲しい⇒ハンドルのセンサー？
・加速度センサの反応がいまいち（急発進がよくある）
・ハンドルセンサの導入

〇ソフト　制御
・制御方法　必要トルク/推定の最大＝ＰＷＭ／256 より押し心地のよい制御手法

〇その他
・モーターの性能調査　ＰＷＭ周波数、ＭＡＸ・ＡＶＥ電流、トルク定数

**Comment by 94yukari** [comment]
![2](https://user-images.githubusercontent.com/7434215/29523674-bfeb3532-86c8-11e7-962e-03adb18974f7.jpg)

**Comment by 94yukari** [comment]
以下issueにしたらチェック
〇ハード
- [x] 減速比を設計しなおす　必要トルク、回転速度  #18
- [x] ゴムタイヤと軸の固定方法の検討
- [x] ゴムタイヤと車輪の接点を柔軟に変えられる感じにする
- [x] 車体との固定箇所も考える
- [x] 穴をあける箇所も検討する

〇電気関係
- [x] 電源スイッチが欲しい⇒ハンドルのセンサー？
- [x] 加速度センサの反応がいまいち（急発進がよくある）
- [x] ハンドルセンサの導入　#13, #12

〇ソフト　制御
- [x] 制御方法　必要トルク/推定の最大＝ＰＷＭ／256 より押し心地のよい制御手法 #14 

〇その他
- [x] モーターの性能調査　ＰＷＭ周波数、ＭＡＸ・ＡＶＥ電流、トルク定数　#19

**Comment by 94yukari** [comment]
ソフトのことについては、トルク制御をしましょうということで、#14 で対応

**Comment by 94yukari** [comment]
改善まとめ
〇ハード設計的な改善点
●減速比関連
・回転速度がはやい
・減速比の設計ミスnow16:1程度だがおそらく60:1ぐらい必要？
・減速比の再設計
**→回転速度は電圧を落とせば対応できる。その点は、制御方法で対応することになった**

●ゴムタイヤ
・取り付けにくい（コツがいる）
・ゴムタイヤと車輪の接点を柔軟に変えられる感じにする
**→改善方法を検討したが、製作は優先順位を下げた**

・タイヤ面とゴムタイヤの接点がシビア
・動力伝達がいい加減なのでタイヤに強く接すると高トルクで動かない
・ゴムタイヤと軸の固定
・ゴムタイヤ延長軸の強度(悪条件だと取れる)
→ゴムタイヤと軸の固定方法の検討
**→上記4点を改善した、モーターボックスを製作した**

●機構
・取り付け軸に対する左右の重さのバランス（モーメントで回転しがち）
・締結部に到達できるか？
・ネジ一つが車体と干渉（ただし、ワッシャを挟めば対処可）
・コの字型のＢＯＸの形状、サドルバンドでの固定は特に問題なし
→車体との固定箇所も考える
→穴をあける箇所も検討する
**→モーターボックスの形の改善で対応済み**

●その他
・物が重い
・8/8の様子だと、空で条件よければ自走できそうな雰囲気
・タイヤに汚れありー＞屋外で使用できるか？

〇電気関係
・電源スイッチが欲しい⇒ハンドルのセンサー？
・加速度センサの反応がいまいち（急発進がよくある）
・ハンドルセンサの導入

〇ソフト　制御
・制御方法　必要トルク/推定の最大＝ＰＷＭ／256 より押し心地のよい制御手法
**→トルク制御の実装**

〇その他
・モーターの性能調査　ＰＷＭ周波数、ＭＡＸ・ＡＶＥ電流、トルク定数
**→モーターの性能は調査済み**

**Comment by 94yukari** [comment]
一部未確認内容もあるが、基本的に対応できたのでcloseとする
